# Generated by Django 3.2.6 on 2021-08-26 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_1', models.CharField(blank=True, max_length=250)),
                ('text_2', models.CharField(blank=True, max_length=250)),
                ('iconName', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('number', models.IntegerField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('amountDue', models.CharField(blank=True, max_length=250)),
                ('dueDate', models.CharField(blank=True, max_length=250)),
                ('isCompleted', models.BooleanField()),
                ('assignedTo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Partener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('details', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.details')),
                ('tasks', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
            ],
        ),
    ]
