# Generated by Django 3.2.6 on 2021-08-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_details_employee_partener_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='isCompleted',
            field=models.BooleanField(blank=True),
        ),
    ]
