# Generated by Django 3.2.6 on 2021-08-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210826_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partener',
            name='details',
        ),
        migrations.RemoveField(
            model_name='partener',
            name='tasks',
        ),
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.details')),
                ('partener', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.partener')),
                ('tasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tasks')),
            ],
        ),
    ]
