# Generated by Django 3.2.6 on 2021-08-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210826_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all',
            name='details',
        ),
        migrations.AddField(
            model_name='all',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, to='api.Details'),
        ),
    ]
