# Generated by Django 3.2.6 on 2021-08-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210827_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='partener',
            name='details',
            field=models.ManyToManyField(blank=True, null=True, to='api.Details'),
        ),
        migrations.AddField(
            model_name='partener',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='api.Tasks'),
        ),
        migrations.DeleteModel(
            name='All',
        ),
    ]
