# Generated by Django 3.2.6 on 2021-08-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210827_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='assignedTo',
        ),
        migrations.AddField(
            model_name='tasks',
            name='assignedTo',
            field=models.ManyToManyField(blank=True, null=True, to='api.Employee'),
        ),
    ]
