# Generated by Django 3.2.6 on 2021-08-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210827_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPartener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('name2', models.CharField(blank=True, max_length=250, null=True)),
                ('name3', models.CharField(blank=True, max_length=250, null=True)),
                ('name4', models.CharField(blank=True, max_length=250, null=True)),
                ('name5', models.CharField(blank=True, max_length=250, null=True)),
                ('name6', models.CharField(blank=True, max_length=250, null=True)),
                ('name7', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
