# Generated by Django 3.2.6 on 2021-08-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210830_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='text_1',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='details',
            name='text_2',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='partener',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='partener',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='amountDue',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='dueDate',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='isCompleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(default=True, max_length=250),
        ),
    ]
