# Generated by Django 3.2.6 on 2021-08-31 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210831_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partener',
            name='details',
            field=models.ManyToManyField(related_name='partener', to='api.Details'),
        ),
    ]
