# Generated by Django 3.2.6 on 2021-08-31 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_partener_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncontent',
            name='course_content',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CourseContent',
        ),
        migrations.DeleteModel(
            name='SectionContent',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
