# Generated by Django 3.2.6 on 2021-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_tasks_assignedto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='text_1',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='details',
            name='text_2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newpartener',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newpartener',
            name='name2',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newpartener',
            name='name3',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newpartener',
            name='name4',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newpartener',
            name='name5',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newpartener',
            name='name6',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='newpartener',
            name='name7',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='partener',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='partener',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='partener',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='api.Tasks'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='amountDue',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='assignedTo',
            field=models.ManyToManyField(to='api.Employee'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='dueDate',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='isCompleted',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
