# Generated by Django 3.2.6 on 2021-08-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210831_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partener',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='api.Tasks'),
        ),
    ]
