# Generated by Django 3.2.6 on 2021-08-31 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_partener_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('details', models.ManyToManyField(related_name='partner', to='api.Details')),
                ('tasks', models.ManyToManyField(blank=True, to='api.Tasks')),
            ],
        ),
        migrations.RenameModel(
            old_name='NewPartener',
            new_name='NewPartner',
        ),
        migrations.DeleteModel(
            name='Partener',
        ),
    ]
