# Generated by Django 3.2.6 on 2021-08-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210831_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpartner',
            old_name='name2',
            new_name='field1',
        ),
        migrations.RenameField(
            model_name='newpartner',
            old_name='name3',
            new_name='field2',
        ),
        migrations.RenameField(
            model_name='newpartner',
            old_name='name4',
            new_name='field3',
        ),
        migrations.RenameField(
            model_name='newpartner',
            old_name='name5',
            new_name='field4',
        ),
        migrations.RenameField(
            model_name='newpartner',
            old_name='name6',
            new_name='field5',
        ),
        migrations.RenameField(
            model_name='newpartner',
            old_name='name7',
            new_name='field6',
        ),
        migrations.AlterField(
            model_name='newpartner',
            name='description',
            field=models.TextField(),
        ),
    ]
