# Generated by Django 3.2.6 on 2021-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210831_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Add_info_1', models.CharField(default='', max_length=100)),
                ('Add_info_2', models.CharField(default='', max_length=100)),
                ('Add_info_3', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Details',
            new_name='DetailsPartner',
        ),
        migrations.AddField(
            model_name='tasks',
            name='details',
            field=models.ManyToManyField(blank=True, to='api.DetailsTask'),
        ),
    ]
