# Generated by Django 3.2.6 on 2021-09-01 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210901_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='details',
            new_name='details_tasks',
        ),
    ]
